// <auto-generated />
namespace Nibo_Full_Stack_Developers_Challenge___Level_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addtotalfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtotalfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202008241303321_Add total field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
